---
apiVersion: apps/v1
kind: Pod
metadata:
  name: mongo
spec:
  containers:
  - name: mongodb
    image: mongo
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "500Mi"
        cpu: "1000m"
    ports:
    - containerPort: 8081
    env:
      - name: MONGODB_INITDB_DATABASE 
        value: contacts
      - name: MONGO_INITDB_ROOT_USERNAME 
        value: username
      - name: MONGO_INITDB_ROOT_PASSWORD 
        value: password
    volumeMounts:
    - mountPath: "/data/db"
      name: mdb
  volumes:
    - name: mdb
      persistentVolumeClaim:
        claimName: mypvc