---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: "/data/db"
          name: mdb
      volumes:
      - name: mdb
        persistentVolumeClaim:
          claimName: mypvc
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 8081
    targetPort: 8081

