---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: books-db-rs
  labels:
    env: dev
    app: books-db
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: books-db
  template:
    metadata:
      labels:
        app: books-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports: 
          - containerPort: 5432
      resources:
        requests:
          cpu: "128Mi"
          memory: "250m"
        limits:
          cpu: "256Mi"
          memory: "500m"
          env:
            - name: POSTGRES_USER
              value: USER
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: booksbd

---
apiVersion: v1
kind: Service
metadata:
  name: books-db-svc
spec:
  type: ClusterIP 
  selector:
    app: books-db
  ports:
  - port: 5432
    targetPort: 5432

      

