---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: books-svc-rs
  labels:
    env: dev
    app: books-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-svc
  template:
    metadata:
      labels:
        app: books-svc
    spec:
      containers:
        - name: books-svc
          image:  shaikkhajaibrahim/libbookssvc:1.0
          ports: 
          - containerPort: 8000
          resources:
            requests:
              cpu: "128m"
              memory: "250Mi"
            limits:
              cpu: "256m"
              memory: "500Mi"
          env:
            - name: DATABASE_URL
              value: “postgresql://:@:5432/“
            - name: SECRET_KEY
              value: ‘YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k’

---
apiVersion: v1
kind: Service
metadata:
  name: books-svc
spec:
  type: ClusterIP 
  selector:
    app: books-svc
  ports:
  - port: 8000
    targetPort: 8000

            
      



