---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lib-rs
  labels:
    env: dev
    app: frontend-lib
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: lib
  template:
    metadata:
      labels:
        app: lib
    spec:
      containers:
        - name: frontend-lib
          image: shaikkhajaibrahim/libwebstore:1.0
          ports:
          - containerPort: 3000
          resources:
            requests:
              cpu: "128m"
              memory: "250Mi"
            limits:
              cpu: "256m"
              memory: "500Mi"
          livenessProbe:
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            tcpSocket:
              port: 8000
          readinessProbe:
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: doc/
              port: 8000
          startupProbe:
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep uvicorn
          envFrom:
          - configMapRef:
              name: frontend-lib-confmap
            
---
apiVersion: v1
kind: Service
metadata:
  name: lib-svc
spec:
  type: ClusterIP
  selector:
    app: lib
  ports:
  - port: 3000
    targetPort: 3000

