---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-db-rs
  labels:
    env: dev
    app: user-db
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports: 
          - containerPort: 5432
          resources:
            requests:
              cpu: "128m"
              memory: "250Mi"
            limits:
              cpu: "256m"
              memory: "500Mi"
            envFrom:
            - secretRef:
                name: users-db-key
          
---
apiVersion: v1
kind: Service
metadata:
  name: user-db-svc
spec:
  type: ClusterIP
  selector:
    app: user-db
  ports:
  - port: 5432
    targetPort: 5432

      

